name: Run Data Workflow via Python

on:
  workflow_dispatch:
  schedule:
    - cron:  '20 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: install python packages
        run: |
          pip install -r requirements.txt
          
      - name: execute py script
        env:
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
          GH_SERILUM_ORG_ACCESS_TOKEN: ${{ secrets.GH_SERILUM_ORG_ACCESS_TOKEN }}
          MODRINTH_API_KEY: ${{ secrets.MODRINTH_API_KEY }}
          PATREON_SERILUM_API_KEY: ${{ secrets.PATREON_SERILUM_API_KEY }}
          RICK_YT_API_KEY: ${{ secrets.RICK_YT_API_KEY }}
          IS_PRODUCTION: ${{ vars.IS_PRODUCTION }}
        run: python run.py
          
      - name: commit files
        run: |
          git config --local user.email "workflow-action@serilum.com"
          git config --local user.name "workflow-action"
          git add -A
          if ! git diff-index --quiet HEAD; then
            FILES=$(git diff --cached --name-only | grep -v '\.min\.json$' | xargs -I{} basename {} | sort -u | tr '\n' ', ' | sed 's/,$//')
            if [ ${#FILES} -gt 63 ]; then
              FILES="${FILES:0:60}..."
            fi
            git commit -m "Updated: $FILES"
          fi
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
